spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password: pass123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # Set to 'none' or 'validate' in production to prevent schema changes
    show-sql: true       # Shows SQL queries in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8081